### ISSUE TITLE
Collection for symfony

### ISSUE THREAD

**Issue by sebastianneubert** [startwind/forrest-directory#1]
- list used ENV variables and there default values:

```bash
bin/console debug:container --env-vars
```

- show routes

```bash
bin/console debug:router
```

- show services and names for autowiring

```bash
bin/console debug:autowiring <searchString>?
```

**Comment by sebastianneubert** [comment]
i help myself and add it to the repository.

could you give me write access? @phmLabs

**Comment by phmLabs** [comment]
@sebastianneubert done
